apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-prod-nginx"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vault.${ARGOCD_ENV_DNS}
    secretName: kasten-tls
  rules:
  - host: vault.${ARGOCD_ENV_DNS}
    http:
      paths:
      - backend:
          service:
            name: vault
            port:
              number: 8200
        path: /
        pathType: Prefix